In [8]:
import pandas as pd

In [9]:
df = pd.read_json("trends_20260406.json")

df.head()

,post_id,title,category,score,num_comments,author,collected_at
0,47655408,Show HN: I built a tiny LLM to demystify how l...,technology,625,80,armanified,2026-04-06 13:16:06
1,47658146,France pulls last gold held in US for $15B gain,technology,279,155,teleforce,2026-04-06 13:16:06
2,47659807,Ask HN: How do systems (or people) detect when...,technology,19,16,elC0mpa,2026-04-06 13:16:07
3,47652007,"Show HN: Real-time AI (audio/video in, voice o...",technology,151,13,karimf,2026-04-06 13:16:07
4,47656981,"Drop, formerly Massdrop, ends most collaborati...",technology,60,17,stevebmark,2026-04-06 13:16:07

In [10]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       110 non-null    int64
 1   title         110 non-null    object
 2   category      110 non-null    object
 3   score         110 non-null    int64
 4   num_comments  110 non-null    int64
 5   author        110 non-null    object
 6   collected_at  110 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 6.1+ KB

(110, 7)

In [11]:
# Remove duplicates
df = df.drop_duplicates(subset="post_id")

# Remove empty titles
df = df[df["title"].notnull()]

# Reset index
df = df.reset_index(drop=True)

df.shape

(99, 7)

In [12]:
df["collected_at"] = pd.to_datetime(df["collected_at"])

In [13]:
df["category"].value_counts()

category
technology       25
worldnews        25
science          19
entertainment    16
sports           14
Name: count, dtype: int64

In [14]:
df.to_csv("cleaned_trend.csv", index=False)